name: remote_pi_identity_example
description: "Demonstrates how to use the remote_pi_identity plugin."
publish_to: 'none'

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter

  remote_pi_identity:
    path: ../

  cryptography: ^2.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
